version: '3.8'
services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "9090:6379"
  chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    depends_on:
        - redis
    entrypoint:
        [ "/app/wait.sh", "--", "redis:9090"]
    command: [ "/app/main" ]
