version: '3.8'
services:
  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

    ports:
       - "6379:6379"
  chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    depends_on:
        - redis
    entrypoint:
        [ "/app/wait.sh", "redis:6379", "--", "/app/start.sh"]
    command:
      - "/app/main"
