version: '3.8'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier
    ports:
       - "6379:6379"
  chat:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    networks:
      - app-tier
    depends_on:
        - redis
    entrypoint:
        [ "/app/wait.sh", "redis:6379", "--", "/app/start.sh"]
    command:
      - "/app/main"
  chat1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - app-tier
    depends_on:
      - redis
    entrypoint:
      [ "/app/wait.sh", "redis:6379", "--", "/app/start.sh" ]
    command:
      - "/app/main"
